// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the THIRD-PARTY file.

//! Virtual Machine Monitor that leverages the Linux Kernel-based Virtual Machine (KVM),
//! and other virtualization features to run a single lightweight micro-virtual
//! machine (microVM).
//#![deny(missing_docs)]

/// Handles setup and initialization a `Vmm` object.
pub mod builder;
/// VM checkpoint state and its on-disk format.
#[cfg(checkpoint)]
pub(crate) mod checkpoint;
pub(crate) mod device_manager;
/// Resource store for configured microVM resources.
pub mod resources;
/// Signal handling utilities.
#[cfg(target_os = "linux")]
pub mod signal_handler;
/// Wrappers over structures used to configure the VMM.
pub mod vmm_config;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
use crate::vmm::linux::vstate;
#[cfg(checkpoint)]
pub(crate) use vstate::checkpoint_supported;

/// Whether this host can restore the checkpoint in `dir`, from its
/// `checkpoint.bin` alone (the RAM image isn't read), without building a VM
/// for it: the reason a restore here would refuse it, if so.
#[cfg(checkpoint)]
pub(crate) fn check_checkpoint_host(dir: &Path) -> std::result::Result<(), String> {
    let checkpoint = Checkpoint::read(dir)?;
    let vcpus = u8::try_from(checkpoint.vcpus.len())
        .map_err(|_| format!("{} vCPUs is more than a VM has", checkpoint.vcpus.len()))?;
    let here = vstate::probe_host(vcpus).map_err(|e| format!("probe this host: {e}"))?;
    checkpoint.host.check(&here)
}

#[cfg(target_os = "macos")]
mod macos;
mod terminal;
pub mod worker;

#[cfg(target_os = "macos")]
use macos::vstate;

#[cfg(target_os = "windows")]
mod windows;
#[cfg(target_os = "windows")]
use crate::vmm::windows::vstate;

use std::fmt::{Display, Formatter};
use std::io;
#[cfg(not(target_os = "windows"))]
use std::os::unix::io::AsRawFd;
#[cfg(checkpoint)]
use std::path::Path;
use std::sync::atomic::{AtomicI32, Ordering};
use std::sync::{Arc, Mutex};
#[cfg(any(target_os = "linux", target_os = "windows"))]
use std::time::Duration;
#[cfg(target_os = "windows")]
use utils::windows::AsRawFd;

#[cfg(checkpoint)]
use crate::vmm::checkpoint::{format::Checkpoint, memory};
use crate::vmm::device_manager::mmio::MMIODeviceManager;
#[cfg(any(target_os = "linux", target_os = "windows"))]
use crate::vmm::vstate::VcpuEvent;
#[cfg(checkpoint)]
use crate::vmm::vstate::VcpuState;
use crate::vmm::vstate::{Vcpu, VcpuHandle, VcpuResponse, Vm};

use arch::{ArchMemoryInfo, InitrdConfig};
#[cfg(target_os = "macos")]
use crossbeam_channel::Sender;
#[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
use devices::fdt;
use devices::legacy::IrqChip;
use devices::virtio::VmmExitObserver;
#[cfg(checkpoint)]
use devices::virtio::persist::VmDevicesState;
use kernel::cmdline::Cmdline as KernelCmdline;
use polly::event_manager::{EventManager, Subscriber};
use utils::epoll::{EpollEvent, EventSet};
use utils::eventfd::EventFd;
#[cfg(any(target_os = "macos", target_os = "linux"))]
use utils::pollable_channel::{PollableChannelReciever, PollableChannelSender};
use vm_memory::GuestMemoryMmap;

/// Success exit code.
pub const FC_EXIT_CODE_OK: u8 = 0;
/// Generic error exit code.
pub const FC_EXIT_CODE_GENERIC_ERROR: u8 = 1;
/// Generic exit code for an error considered not possible to occur if the program logic is sound.
#[cfg(target_os = "linux")]
pub const FC_EXIT_CODE_UNEXPECTED_ERROR: u8 = 2;
/// Errors associated with the VMM internal logic. These errors cannot be generated by direct user
/// input, but can result from bad configuration of the host (for example if Firecracker doesn't
/// have permissions to open the KVM fd).
#[derive(Debug)]
#[allow(unused)]
pub enum Error {
    /// This error is thrown by the minimal boot loader implementation.
    ConfigureSystem(arch::Error),
    /// Legacy devices work with Event file descriptors and the creation can fail because
    /// of resource exhaustion.
    #[cfg(target_arch = "x86_64")]
    CreateLegacyDevice(device_manager::legacy::Error),
    /// Cannot read from an Event file descriptor.
    EventFd(io::Error),
    /// Cannot open /dev/kvm. Either the host does not have KVM or Firecracker does not have
    /// permission to open the file descriptor.
    KvmContext(vstate::Error),
    #[cfg(target_arch = "x86_64")]
    /// Cannot add devices to the Legacy I/O Bus.
    LegacyIOBus(device_manager::legacy::Error),
    /// Cannot add a device to the MMIO Bus.
    RegisterMMIODevice(device_manager::mmio::Error),
    #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
    /// Cannot generate or write FDT
    SetupFDT(devices::fdt::Error),
    /// Vcpu error.
    Vcpu(vstate::Error),
    /// Cannot send event to vCPU.
    VcpuEvent(vstate::Error),
    /// Cannot create a vCPU handle.
    VcpuHandle(vstate::Error),
    /// vCPU resume failed.
    VcpuResume,
    /// Vm error.
    Vm(vstate::Error),
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        use self::Error::*;

        match self {
            ConfigureSystem(e) => write!(f, "System configuration error: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            CreateLegacyDevice(e) => write!(f, "Error creating legacy device: {e:?}"),
            EventFd(e) => write!(f, "Event fd error: {e}"),
            KvmContext(e) => write!(f, "Failed to validate KVM support: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            LegacyIOBus(e) => write!(f, "Cannot add devices to the legacy I/O Bus. {e}"),
            RegisterMMIODevice(e) => write!(f, "Cannot add a device to the MMIO Bus. {e}"),
            #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
            SetupFDT(e) => write!(f, "Error generating or writing FDT: {e:?}"),
            Vcpu(e) => write!(f, "Vcpu error: {e}"),
            VcpuEvent(e) => write!(f, "Cannot send event to vCPU. {e:?}"),
            VcpuHandle(e) => write!(f, "Cannot create a vCPU handle. {e}"),
            VcpuResume => write!(f, "vCPUs resume failed."),
            Vm(e) => write!(f, "Vm error: {e}"),
        }
    }
}

/// Shorthand result type for internal VMM commands.
pub type Result<T> = std::result::Result<T, Error>;

/// Contains the state and associated methods required for the Firecracker VMM.
pub struct Vmm {
    // Guest VM core resources.
    pub(crate) guest_memory: GuestMemoryMmap,
    pub(crate) arch_memory_info: ArchMemoryInfo,

    pub(crate) kernel_cmdline: KernelCmdline,

    pub(crate) vcpus_handles: Vec<VcpuHandle>,
    pub(crate) exit_evt: EventFd,
    pub(crate) vm: Vm,
    pub(crate) exit_observers: Vec<Arc<Mutex<dyn VmmExitObserver>>>,
    pub(crate) exit_code: Arc<AtomicI32>,

    // Guest VM devices.
    pub(crate) mmio_device_manager: MMIODeviceManager,

    // Out-of-band live pause/resume requests: the C API sends `VmCtl` from
    // another thread; the event loop freezes or wakes the vCPUs. A single
    // channel rather than one eventfd per operation, so the event loop observes
    // the requests in the order they were made. Device worker threads are
    // notify-driven, so a frozen guest leaves them idle without explicit
    // handling.
    #[cfg(any(target_os = "macos", target_os = "linux"))]
    pub(crate) vm_ctl_tx: PollableChannelSender<VmCtl>,
    #[cfg(any(target_os = "macos", target_os = "linux"))]
    pub(crate) vm_ctl_rx: PollableChannelReciever<VmCtl>,
    #[cfg(any(target_os = "macos", target_os = "linux"))]
    pub(crate) paused: bool,
    /// The VM-wide kvmclock at pause, restored on resume so the guest's clock
    /// doesn't jump by the time spent paused.
    #[cfg(all(target_os = "linux", target_arch = "x86_64"))]
    pub(crate) paused_clock: Option<kvm_bindings::kvm_clock_data>,
    #[cfg(target_os = "macos")]
    pub(crate) paused_at: u64,
    /// The devices' I/O is stopped for a checkpoint (see [`Vmm::save`]);
    /// [`Vmm::resume`] restarts it.
    #[cfg(checkpoint)]
    pub(crate) devices_quiesced: bool,
}

/// Out-of-band request to the running VM's event loop.
#[cfg(any(target_os = "macos", target_os = "linux"))]
#[derive(Debug, Clone)]
pub enum VmCtl {
    /// Pause; the outcome is sent back once every vCPU is parked.
    Pause(crossbeam_channel::Sender<std::result::Result<(), String>>),
    /// Resume; the outcome is sent back once every vCPU is running again.
    Resume(crossbeam_channel::Sender<std::result::Result<(), String>>),
    /// Save the VM to a new checkpoint directory; see [`Vmm::save`].
    #[cfg(checkpoint)]
    Save {
        dir: std::path::PathBuf,
        reply: crossbeam_channel::Sender<std::result::Result<(), String>>,
    },
}

impl Vmm {
    /// Starts the microVM vcpus.
    pub fn start_vcpus(&mut self, vcpus: Vec<Vcpu>) -> Result<()> {
        self.spawn_vcpus(vcpus)?;

        // The vcpus start off in the `Paused` state, let them run.
        self.resume_vcpus()?;

        Ok(())
    }

    /// Starts the vCPU threads but leaves them parked, for a restore to load
    /// their state; [`Vmm::resume`] runs them.
    #[cfg(checkpoint)]
    fn start_vcpus_paused(&mut self, vcpus: Vec<Vcpu>) -> Result<()> {
        self.spawn_vcpus(vcpus)?;
        self.paused = true;
        Ok(())
    }

    fn spawn_vcpus(&mut self, mut vcpus: Vec<Vcpu>) -> Result<()> {
        let vcpu_count = vcpus.len();

        Vcpu::register_kick_signal_handler();

        self.vcpus_handles.reserve(vcpu_count);

        for mut vcpu in vcpus.drain(..) {
            vcpu.set_mmio_bus(self.mmio_device_manager.bus.clone());

            self.vcpus_handles
                .push(vcpu.start_threaded().map_err(Error::VcpuHandle)?);
        }
        Ok(())
    }

    /// Sends a resume command to the vcpus.
    #[cfg(target_os = "linux")]
    pub fn resume_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Resume)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Resumed) => (),
                _ => return Err(Error::VcpuResume),
            }
        }
        Ok(())
    }

    #[cfg(target_os = "macos")]
    pub fn resume_vcpus(&mut self) -> Result<()> {
        Ok(())
    }

    #[cfg(target_os = "windows")]
    pub fn resume_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Resume)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Resumed) => (),
                _ => return Err(Error::VcpuResume),
            }
        }
        Ok(())
    }

    /// Sender for live [`VmCtl`] requests. The event loop runs [`Vmm::pause`] /
    /// [`Vmm::resume`] in response.
    #[cfg(any(target_os = "macos", target_os = "linux"))]
    pub fn vm_ctl_sender(&self) -> PollableChannelSender<VmCtl> {
        self.vm_ctl_tx.clone()
    }

    /// Freeze every vCPU at an instruction boundary. Reversible via [`Vmm::resume`];
    /// the guest's virtual counter is held so timers don't fire en masse on wake.
    /// Idempotent: pausing an already-paused VM is a no-op.
    #[cfg(target_os = "macos")]
    pub fn pause(&mut self) -> std::result::Result<(), String> {
        use crate::vmm::vstate::{VcpuEvent, VcpuResponse};
        if self.paused {
            return Ok(());
        }
        for h in &self.vcpus_handles {
            h.send_event(VcpuEvent::Pause)
                .map_err(|e| format!("vcpu pause event: {e:?}"))?;
            hvf::vcpu_request_exit(h.hvf_id()).map_err(|e| format!("vcpu_request_exit: {e:?}"))?;
        }
        for h in &self.vcpus_handles {
            match h.response_receiver().recv() {
                Ok(VcpuResponse::Paused) => {}
                Ok(other) => return Err(format!("unexpected vcpu response: {other:?}")),
                Err(e) => return Err(format!("vcpu response: {e:?}")),
            }
        }
        self.paused_at = unsafe { hvf::mach_absolute_time() };
        self.paused = true;
        Ok(())
    }

    /// Wake every vCPU previously frozen by [`Vmm::pause`], advancing the vtimer
    /// offset by the time spent paused. Idempotent: resuming a running VM is a
    /// no-op.
    #[cfg(target_os = "macos")]
    pub fn resume(&mut self) -> std::result::Result<(), String> {
        use crate::vmm::vstate::{VcpuEvent, VcpuResponse};
        if !self.paused {
            return Ok(());
        }
        let paused_ticks = unsafe { hvf::mach_absolute_time() }.saturating_sub(self.paused_at);
        for h in &self.vcpus_handles {
            h.send_event(VcpuEvent::Resume(paused_ticks))
                .map_err(|e| format!("vcpu resume event: {e:?}"))?;
        }
        for h in &self.vcpus_handles {
            match h.response_receiver().recv() {
                Ok(VcpuResponse::Resumed) => {}
                Ok(other) => return Err(format!("unexpected vcpu response: {other:?}")),
                Err(e) => return Err(format!("vcpu response: {e:?}")),
            }
        }
        self.paused = false;
        Ok(())
    }

    /// Freeze every vCPU at an instruction boundary (each is kicked out of
    /// KVM_RUN by its signal). Reversible via [`Vmm::resume`]; the guest's
    /// clocks are held across the pause. Idempotent.
    #[cfg(target_os = "linux")]
    pub fn pause(&mut self) -> std::result::Result<(), String> {
        if self.paused {
            return Ok(());
        }
        for h in &self.vcpus_handles {
            h.send_event(VcpuEvent::Pause)
                .map_err(|e| format!("vcpu pause event: {e:?}"))?;
        }
        for h in &self.vcpus_handles {
            match h.response_receiver().recv() {
                Ok(VcpuResponse::Paused) => {}
                Ok(other) => return Err(format!("unexpected vcpu response: {other:?}")),
                Err(e) => return Err(format!("vcpu response: {e:?}")),
            }
        }
        // kvmclock is VM-wide on x86 (arm64's counter is saved per vCPU).
        #[cfg(target_arch = "x86_64")]
        {
            self.paused_clock = Some(
                self.vm
                    .fd()
                    .get_clock()
                    .map_err(|e| format!("KVM_GET_CLOCK: {e}"))?,
            );
        }
        self.paused = true;
        Ok(())
    }

    /// Wake every vCPU frozen by [`Vmm::pause`], with the guest's clocks
    /// continuing from where they stopped, after restarting the device I/O a
    /// checkpoint stopped. Idempotent.
    #[cfg(target_os = "linux")]
    pub fn resume(&mut self) -> std::result::Result<(), String> {
        #[cfg(checkpoint)]
        self.rearm_devices();
        if !self.paused {
            return Ok(());
        }
        #[cfg(target_arch = "x86_64")]
        if let Some(mut clock) = self.paused_clock.take() {
            // Only the clock value is restored; the flags KVM_GET_CLOCK
            // reports (e.g. TSC-stable) aren't valid input to KVM_SET_CLOCK.
            clock.flags = 0;
            self.vm
                .fd()
                .set_clock(&clock)
                .map_err(|e| format!("KVM_SET_CLOCK: {e}"))?;
        }
        for h in &self.vcpus_handles {
            h.send_event(VcpuEvent::Resume)
                .map_err(|e| format!("vcpu resume event: {e:?}"))?;
        }
        for h in &self.vcpus_handles {
            match h.response_receiver().recv() {
                Ok(VcpuResponse::Resumed) => {}
                Ok(other) => return Err(format!("unexpected vcpu response: {other:?}")),
                Err(e) => return Err(format!("vcpu response: {e:?}")),
            }
        }
        self.paused = false;
        Ok(())
    }

    /// Configures the system for boot.
    #[allow(clippy::too_many_arguments)]
    pub fn configure_system(
        &self,
        vcpus: &[Vcpu],
        _intc: &IrqChip,
        initrd: &Option<InitrdConfig>,
        _smbios_oem_strings: &Option<Vec<String>>,
        _acpi_enabled: bool,
        _virtio_mmio_devices: &[(u64, u32)],
        _pvh: bool,
    ) -> Result<()> {
        #[cfg(target_arch = "x86_64")]
        {
            let cmdline_len = if cfg!(feature = "tee") {
                arch::x86_64::layout::CMDLINE_SEV_SIZE
            } else {
                self.kernel_cmdline.len() + 1
            };

            arch::x86_64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                vm_memory::GuestAddress(arch::x86_64::layout::CMDLINE_START),
                cmdline_len,
                initrd,
                vcpus.len() as u8,
                _pvh,
                _acpi_enabled,
                _virtio_mmio_devices,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            let vcpu_mpidr = vcpus.iter().map(|cpu| cpu.get_mpidr()).collect();
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpu_mpidr,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            arch::aarch64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                _smbios_oem_strings,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "riscv64")]
        {
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpus.len() as u32,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;

            arch::riscv64::configure_system(&self.guest_memory, _smbios_oem_strings)
                .map_err(Error::ConfigureSystem)?;
        }

        Ok(())
    }

    /// Returns a reference to the inner `GuestMemoryMmap` object if present, or `None` otherwise.
    pub fn guest_memory(&self) -> &GuestMemoryMmap {
        &self.guest_memory
    }

    /// Waits for all vCPUs to exit and terminates the Firecracker process.
    pub fn stop(&mut self, exit_code: i32) {
        info!("Vmm is stopping.");

        for observer in &self.exit_observers {
            observer
                .lock()
                .expect("Poisoned mutex for exit observer")
                .on_vmm_exit();
        }

        // Exit from Firecracker using the provided exit code. Safe because we're terminating
        // the process anyway.
        unsafe {
            libc::_exit(exit_code);
        }
    }

    /// Returns a reference to the inner KVM Vm object.
    #[cfg(feature = "tee")]
    pub fn kvm_vm(&self) -> &Vm {
        &self.vm
    }

    #[cfg(target_os = "macos")]
    pub fn add_mapping(
        &self,
        reply_sender: Sender<bool>,
        host_addr: u64,
        guest_addr: u64,
        len: u64,
    ) {
        self.vm
            .add_mapping(reply_sender, host_addr, guest_addr, len);
    }

    #[cfg(target_os = "macos")]
    pub fn remove_mapping(&self, reply_sender: Sender<bool>, guest_addr: u64, len: u64) {
        self.vm.remove_mapping(reply_sender, guest_addr, len);
    }
}

/// Checkpoints: saving a running VM to a directory, and restoring one into a
/// new VMM.
#[cfg(checkpoint)]
impl Vmm {
    /// Saves the VM to `dir`, which must not exist yet (its parent must). On
    /// success the VM is left paused with its device I/O stopped, so the
    /// caller can copy its disks at the instant the checkpoint captured;
    /// [`Vmm::resume`] runs it on. On failure the VM is back as it was and
    /// `dir` doesn't exist.
    pub fn save(&mut self, dir: &Path) -> std::result::Result<(), String> {
        if let Some(why) = self.mmio_device_manager.checkpoint_refusal() {
            return Err(format!("can't checkpoint this VM: {why}"));
        }
        let (was_paused, was_quiesced) = (self.paused, self.devices_quiesced);
        self.pause()?;
        let saved = self.save_paused(dir);
        if let Err(e) = &saved {
            if !was_quiesced {
                self.rearm_devices();
            }
            if !was_paused {
                self.resume()
                    .map_err(|r| format!("{e}; then resuming the VM failed: {r}"))?;
            }
        }
        saved
    }

    fn save_paused(&mut self, dir: &Path) -> std::result::Result<(), String> {
        self.devices_quiesced = true;
        self.mmio_device_manager.quiesce_devices()?;
        let vcpus = self.save_vcpu_states()?;
        let vm = self.vm.save_state().map_err(|e| e.to_string())?;
        let host = self
            .vm
            .host_record(vcpus.first().ok_or("the VM has no vCPUs")?);
        let device_state = self.mmio_device_manager.snapshot_devices()?.to_bytes()?;
        Checkpoint {
            host,
            ram: memory::layout(&self.guest_memory),
            devices: self.mmio_device_manager.device_ids(),
            vm,
            vcpus,
            device_state,
        }
        .save(dir, &self.guest_memory)
    }

    fn rearm_devices(&mut self) {
        if std::mem::take(&mut self.devices_quiesced) {
            self.mmio_device_manager.rearm_devices();
        }
    }

    /// Restores `checkpoint` into this VM instead of booting it. The VM was
    /// built for it: the checkpoint's vCPU count, RAM layout (holding the
    /// checkpoint's RAM) and devices; `vcpus` are created but not started.
    /// The VM is left paused: [`Vmm::resume`] runs the guest on from where it
    /// was saved.
    pub(crate) fn restore(
        &mut self,
        checkpoint: Checkpoint,
        vcpus: Vec<Vcpu>,
    ) -> std::result::Result<(), String> {
        let Checkpoint {
            devices,
            vm,
            vcpus: vcpu_states,
            device_state,
            ..
        } = checkpoint;
        let device_state = VmDevicesState::from_bytes(&device_state)?;
        self.vm.restore_state(&vm).map_err(|e| e.to_string())?;
        // The vCPUs' TSCs move on with the kvmclock restore_state moved on;
        // an arm64 vCPU moves its counter on as it loads its state.
        #[cfg(target_arch = "x86_64")]
        let vcpu_states = {
            let mut vcpu_states = vcpu_states;
            self.vm
                .rebase_vcpu_tsc(&vm, &mut vcpu_states)
                .map_err(|e| e.to_string())?;
            vcpu_states
        };
        // Before the vCPU threads start, so that a VM with other devices is
        // refused without leaving any behind.
        self.mmio_device_manager
            .restore_devices(&devices, &device_state)?;
        self.start_vcpus_paused(vcpus).map_err(|e| e.to_string())?;
        self.restore_vcpu_states(vcpu_states)?;
        self.mmio_device_manager.replay_restored_interrupts();
        Ok(())
    }

    /// The state of every vCPU; they must be paused.
    fn save_vcpu_states(&self) -> std::result::Result<Vec<VcpuState>, String> {
        let events = self
            .vcpus_handles
            .iter()
            .map(|_| VcpuEvent::SaveState)
            .collect();
        self.ask_vcpus(events)
            .into_iter()
            .enumerate()
            .map(|(i, answer)| match answer {
                Ok(VcpuResponse::SavedState(state)) => Ok(*state),
                Ok(VcpuResponse::SaveFailed(e)) => Err(format!("vCPU {i}: {e}")),
                Ok(other) => Err(format!("vCPU {i}: unexpected response {other:?}")),
                Err(e) => Err(format!("vCPU {i}: {e}")),
            })
            .collect()
    }

    /// Loads each paused vCPU with its state, in vCPU order.
    fn restore_vcpu_states(&self, states: Vec<VcpuState>) -> std::result::Result<(), String> {
        let events = states
            .into_iter()
            .map(|state| VcpuEvent::RestoreState(Box::new(state)))
            .collect();
        for (i, answer) in self.ask_vcpus(events).into_iter().enumerate() {
            match answer {
                Ok(VcpuResponse::RestoredState) => {}
                Ok(VcpuResponse::RestoreFailed(e)) => return Err(format!("vCPU {i}: {e}")),
                Ok(other) => return Err(format!("vCPU {i}: unexpected response {other:?}")),
                Err(e) => return Err(format!("vCPU {i}: {e}")),
            }
        }
        Ok(())
    }

    /// Hands the first vCPUs one event each and collects every answer, even
    /// after a failure, so that none is left behind for a later request. The
    /// vCPUs must be paused: their paused loop answers.
    fn ask_vcpus(&self, events: Vec<VcpuEvent>) -> Vec<std::result::Result<VcpuResponse, String>> {
        let asked = &self.vcpus_handles[..events.len().min(self.vcpus_handles.len())];
        for (h, event) in asked.iter().zip(events) {
            // The kick only matters to a running vCPU: a paused one reads the
            // event anyway, and its answer is collected below.
            if let Err(e) = h.send_event(event) {
                warn!("vcpu kick: {e}");
            }
        }
        asked
            .iter()
            .map(|h| h.response_receiver().recv().map_err(|e| e.to_string()))
            .collect()
    }
}

impl Subscriber for Vmm {
    /// Handle a read event (EPOLLIN).
    fn process(&mut self, event: &EpollEvent, _: &mut EventManager) {
        let source = event.fd();
        let event_set = event.event_set();

        #[cfg(any(target_os = "macos", target_os = "linux"))]
        if source == self.vm_ctl_rx.as_raw_fd() && event_set == EventSet::IN {
            while let Ok(Some(req)) = self.vm_ctl_rx.try_recv() {
                let (op, res, reply) = match req {
                    VmCtl::Pause(reply) => ("pause", self.pause(), reply),
                    VmCtl::Resume(reply) => ("resume", self.resume(), reply),
                    #[cfg(checkpoint)]
                    VmCtl::Save { dir, reply } => ("save", self.save(&dir), reply),
                };
                if let Err(e) = &res {
                    error!("vm {op} failed: {e}");
                }
                // The caller may have given up waiting; nothing to do then.
                let _ = reply.send(res);
            }
            return;
        }

        if source == self.exit_evt.as_raw_fd() && event_set == EventSet::IN {
            let _ = self.exit_evt.read();
            // Query each vcpu for the exit_code.
            // If the exit_code can't be found on any vcpu, it means that the exit signal
            // has been issued by the i8042 controller in which case we exit with
            // FC_EXIT_CODE_OK.
            //
            // The exit code set up by the guest takes preference over the one reported
            // by either a vcpu or the i8042 controller.
            let vcpu_exit_code = self
                .vcpus_handles
                .iter()
                .find_map(|handle| match handle.response_receiver().try_recv() {
                    Ok(VcpuResponse::Exited(exit_code)) => Some(exit_code),
                    _ => None,
                })
                .unwrap_or(FC_EXIT_CODE_OK);
            let vmm_exit_code = self.exit_code.load(Ordering::SeqCst);
            let exit_code = if vmm_exit_code != i32::MAX {
                debug!("using vmm exit code: {vmm_exit_code}");
                vmm_exit_code
            } else {
                debug!("using vcpu exit code: {vcpu_exit_code}");
                vcpu_exit_code as i32
            };
            self.stop(exit_code);
        } else {
            error!("Spurious EventManager event for handler: Vmm");
        }
    }

    fn interest_list(&self) -> Vec<EpollEvent> {
        // `vm_ctl_rx` is pushed only on macOS and Linux, so `mut` is unused elsewhere.
        #[allow(unused_mut)]
        let mut list = vec![EpollEvent::new(
            EventSet::IN,
            self.exit_evt.as_raw_fd() as u64,
        )];
        #[cfg(any(target_os = "macos", target_os = "linux"))]
        list.push(EpollEvent::new(
            EventSet::IN,
            self.vm_ctl_rx.as_raw_fd() as u64,
        ));
        list
    }
}
