// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the THIRD-PARTY file.

//! Virtual Machine Monitor that leverages the Linux Kernel-based Virtual Machine (KVM),
//! and other virtualization features to run a single lightweight micro-virtual
//! machine (microVM).
//#![deny(missing_docs)]

#[macro_use]
extern crate log;

/// Handles setup and initialization a `Vmm` object.
pub mod builder;
pub(crate) mod device_manager;
/// Resource store for configured microVM resources.
pub mod resources;
/// Guest-memory snapshot serialization (cold-to-disk).
pub mod snapshot;
/// Signal handling utilities.
#[cfg(target_os = "linux")]
pub mod signal_handler;
/// Wrappers over structures used to configure the VMM.
pub mod vmm_config;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
use crate::linux::vstate;
#[cfg(target_os = "macos")]
mod macos;
mod terminal;
pub mod worker;

#[cfg(target_os = "macos")]
use macos::vstate;

use std::fmt::{Display, Formatter};
use std::io;
use std::os::unix::io::AsRawFd;
use std::sync::atomic::{AtomicI32, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

#[cfg(target_arch = "x86_64")]
use crate::device_manager::legacy::PortIODeviceManager;
use crate::device_manager::mmio::MMIODeviceManager;
use crate::vstate::{Vcpu, VcpuEvent, VcpuHandle, VcpuResponse, Vm};

use arch::{ArchMemoryInfo, InitrdConfig};
#[cfg(target_os = "macos")]
use crossbeam_channel::Sender;
#[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
use devices::fdt;
use devices::legacy::IrqChip;
use devices::virtio::VmmExitObserver;
use devices::{BusDevice, DeviceType};
use kernel::cmdline::Cmdline as KernelCmdline;
use polly::event_manager::{self, EventManager, Subscriber};
use utils::epoll::{EpollEvent, EventSet};
use utils::eventfd::EventFd;
use vm_memory::GuestMemoryMmap;

/// Success exit code.
pub const FC_EXIT_CODE_OK: u8 = 0;
/// Generic error exit code.
pub const FC_EXIT_CODE_GENERIC_ERROR: u8 = 1;
/// Generic exit code for an error considered not possible to occur if the program logic is sound.
pub const FC_EXIT_CODE_UNEXPECTED_ERROR: u8 = 2;
/// Firecracker was shut down after intercepting a restricted system call.
pub const FC_EXIT_CODE_BAD_SYSCALL: u8 = 148;
/// Firecracker was shut down after intercepting `SIGBUS`.
pub const FC_EXIT_CODE_SIGBUS: u8 = 149;
/// Firecracker was shut down after intercepting `SIGSEGV`.
pub const FC_EXIT_CODE_SIGSEGV: u8 = 150;
/// Bad configuration for microvm's resources, when using a single json.
pub const FC_EXIT_CODE_BAD_CONFIGURATION: u8 = 152;
/// Command line arguments parsing error.
pub const FC_EXIT_CODE_ARG_PARSING: u8 = 153;

/// Errors associated with the VMM internal logic. These errors cannot be generated by direct user
/// input, but can result from bad configuration of the host (for example if Firecracker doesn't
/// have permissions to open the KVM fd).
#[derive(Debug)]
pub enum Error {
    /// This error is thrown by the minimal boot loader implementation.
    ConfigureSystem(arch::Error),
    /// Legacy devices work with Event file descriptors and the creation can fail because
    /// of resource exhaustion.
    #[cfg(target_arch = "x86_64")]
    CreateLegacyDevice(device_manager::legacy::Error),
    /// Cannot read from an Event file descriptor.
    EventFd(io::Error),
    /// Polly error wrapper.
    EventManager(event_manager::Error),
    /// I8042 Error.
    #[cfg(target_arch = "x86_64")]
    I8042Error(devices::legacy::I8042DeviceError),
    /// Cannot access kernel file.
    KernelFile(io::Error),
    /// Cannot open /dev/kvm. Either the host does not have KVM or Firecracker does not have
    /// permission to open the file descriptor.
    KvmContext(vstate::Error),
    #[cfg(target_arch = "x86_64")]
    /// Cannot add devices to the Legacy I/O Bus.
    LegacyIOBus(device_manager::legacy::Error),
    /// Cannot load command line.
    LoadCommandline(kernel::cmdline::Error),
    /// Cannot add a device to the MMIO Bus.
    RegisterMMIODevice(device_manager::mmio::Error),
    /// Write to the serial console failed.
    Serial(io::Error),
    #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
    /// Cannot generate or write FDT
    SetupFDT(devices::fdt::Error),
    /// Cannot create Timer file descriptor.
    TimerFd(io::Error),
    /// Vcpu error.
    Vcpu(vstate::Error),
    /// Cannot send event to vCPU.
    VcpuEvent(vstate::Error),
    /// Cannot create a vCPU handle.
    VcpuHandle(vstate::Error),
    /// vCPU pause failed.
    VcpuPause,
    /// vCPU resume failed.
    VcpuResume,
    /// Cannot spawn a new Vcpu thread.
    VcpuSpawn(std::io::Error),
    /// Vm error.
    Vm(vstate::Error),
    /// Guest-memory / device checkpoint or restore failure.
    Snapshot(String),
    /// vCPU state capture/restore failure.
    VcpuSnapshot(String),
    /// Error thrown by observer object on Vmm initialization.
    VmmObserverInit(utils::errno::Error),
    /// Error thrown by observer object on Vmm teardown.
    VmmObserverTeardown(utils::errno::Error),
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        use self::Error::*;

        match self {
            ConfigureSystem(e) => write!(f, "System configuration error: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            CreateLegacyDevice(e) => write!(f, "Error creating legacy device: {e:?}"),
            EventFd(e) => write!(f, "Event fd error: {e}"),
            EventManager(e) => write!(f, "Event manager error: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            I8042Error(e) => write!(f, "I8042 error: {e}"),
            KernelFile(e) => write!(f, "Cannot access kernel file: {e}"),
            KvmContext(e) => write!(f, "Failed to validate KVM support: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            LegacyIOBus(e) => write!(f, "Cannot add devices to the legacy I/O Bus. {e}"),
            LoadCommandline(e) => write!(f, "Cannot load command line: {e}"),
            RegisterMMIODevice(e) => write!(f, "Cannot add a device to the MMIO Bus. {e}"),
            Serial(e) => write!(f, "Error writing to the serial console: {e:?}"),
            #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
            SetupFDT(e) => write!(f, "Error generating or writing FDT: {e:?}"),
            TimerFd(e) => write!(f, "Error creating timer fd: {e}"),
            Vcpu(e) => write!(f, "Vcpu error: {e}"),
            VcpuEvent(e) => write!(f, "Cannot send event to vCPU. {e:?}"),
            VcpuHandle(e) => write!(f, "Cannot create a vCPU handle. {e}"),
            VcpuPause => write!(f, "vCPUs pause failed."),
            VcpuResume => write!(f, "vCPUs resume failed."),
            Snapshot(e) => write!(f, "Snapshot error: {e}"),
            VcpuSnapshot(e) => write!(f, "vCPU snapshot error: {e}"),
            VcpuSpawn(e) => write!(f, "Cannot spawn Vcpu thread: {e}"),
            Vm(e) => write!(f, "Vm error: {e}"),
            VmmObserverInit(e) => write!(
                f,
                "Error thrown by observer object on Vmm initialization: {e}"
            ),
            VmmObserverTeardown(e) => {
                write!(f, "Error thrown by observer object on Vmm teardown: {e}")
            }
        }
    }
}

/// Trait for objects that need custom initialization and teardown during the Vmm lifetime.
pub trait VmmEventsObserver {
    /// This function will be called during microVm boot.
    fn on_vmm_boot(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
    /// This function will be called on microVm teardown.
    fn on_vmm_stop(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
}

/// Shorthand result type for internal VMM commands.
pub type Result<T> = std::result::Result<T, Error>;

/// Contains the state and associated methods required for the Firecracker VMM.
/// VMM run state, observable via the control socket (and used to gate
/// pause/resume transitions). The warm tier lives between Running and Paused.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum VmmRunState {
    Running,
    Pausing,
    Paused,
    Resuming,
}

impl VmmRunState {
    /// Lowercase string for the control-socket STATUS reply.
    pub fn as_str(self) -> &'static str {
        match self {
            VmmRunState::Running => "running",
            VmmRunState::Pausing => "pausing",
            VmmRunState::Paused => "paused",
            VmmRunState::Resuming => "resuming",
        }
    }
}

/// The non-memory half of a VM checkpoint: VM-level state (GIC distributor),
/// per-vCPU register state, and virtio device runtime state. Guest RAM is
/// streamed separately (see `snapshot::write_guest_memory`). Serializes to a
/// length-prefixed blob (`checkpoint.bin`); no cross-version compatibility.
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
pub struct VmCheckpoint {
    pub vm_state: vstate::VmState,
    pub vcpu_states: Vec<vstate::VcpuState>,
    pub devices: devices::virtio::persist::VmDevicesState,
}

/// Magic at the head of `checkpoint.bin` ("KRUCSNAP", little-endian). Guards
/// against restoring a truncated, garbage, or wrong-format file: a clean refuse
/// instead of a confusing deserialize panic deep in a section parse.
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
pub const CHECKPOINT_MAGIC: u64 = 0x4b5255_4353_4e4150; // "KRUCSNAP"
/// On-disk checkpoint format version. Bumped on any layout change — there is no
/// cross-version compatibility (the manifest's proto_ver mirrors this).
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
pub const CHECKPOINT_VERSION: u32 = 1;

#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
impl VmCheckpoint {
    pub fn serialize(&self) -> Vec<u8> {
        fn put(out: &mut Vec<u8>, b: &[u8]) {
            out.extend_from_slice(&(b.len() as u32).to_le_bytes());
            out.extend_from_slice(b);
        }
        let mut out = Vec::new();
        out.extend_from_slice(&CHECKPOINT_MAGIC.to_le_bytes());
        out.extend_from_slice(&CHECKPOINT_VERSION.to_le_bytes());
        put(&mut out, &self.vm_state.serialize());
        out.extend_from_slice(&(self.vcpu_states.len() as u32).to_le_bytes());
        for v in &self.vcpu_states {
            put(&mut out, &v.serialize());
        }
        put(&mut out, &self.devices.to_bytes().unwrap_or_default());
        out
    }

    pub fn deserialize(bytes: &[u8]) -> std::result::Result<VmCheckpoint, String> {
        fn take<'a>(b: &'a [u8], pos: &mut usize) -> std::result::Result<&'a [u8], String> {
            if *pos + 4 > b.len() {
                return Err("checkpoint truncated (length header)".to_string());
            }
            let len = u32::from_le_bytes(b[*pos..*pos + 4].try_into().unwrap()) as usize;
            *pos += 4;
            if *pos + len > b.len() {
                return Err("checkpoint truncated (section)".to_string());
            }
            let s = &b[*pos..*pos + len];
            *pos += len;
            Ok(s)
        }
        let mut pos = 0usize;
        // Header: magic + version, before any section.
        if bytes.len() < 12 {
            return Err("checkpoint truncated (header)".to_string());
        }
        let magic = u64::from_le_bytes(bytes[0..8].try_into().unwrap());
        if magic != CHECKPOINT_MAGIC {
            return Err(format!("bad checkpoint magic {magic:#x} (not a krucible checkpoint)"));
        }
        let ver = u32::from_le_bytes(bytes[8..12].try_into().unwrap());
        if ver != CHECKPOINT_VERSION {
            return Err(format!(
                "checkpoint version {ver} != {CHECKPOINT_VERSION} (incompatible — re-snapshot)"
            ));
        }
        pos = 12;
        let vm_state = vstate::VmState::deserialize(take(bytes, &mut pos)?)?;
        if pos + 4 > bytes.len() {
            return Err("checkpoint truncated (vcpu count)".to_string());
        }
        let n = u32::from_le_bytes(bytes[pos..pos + 4].try_into().unwrap()) as usize;
        pos += 4;
        let mut vcpu_states = Vec::with_capacity(n);
        for _ in 0..n {
            vcpu_states.push(vstate::VcpuState::deserialize(take(bytes, &mut pos)?)?);
        }
        let devices =
            devices::virtio::persist::VmDevicesState::from_bytes(take(bytes, &mut pos)?)?;
        Ok(VmCheckpoint {
            vm_state,
            vcpu_states,
            devices,
        })
    }
}

pub struct Vmm {
    // Guest VM core resources.
    guest_memory: GuestMemoryMmap,
    arch_memory_info: ArchMemoryInfo,

    kernel_cmdline: KernelCmdline,

    vcpus_handles: Vec<VcpuHandle>,
    exit_evt: EventFd,
    vm: Vm,
    exit_observers: Vec<Arc<Mutex<dyn VmmExitObserver>>>,
    exit_code: Arc<AtomicI32>,

    // Guest VM devices.
    mmio_device_manager: MMIODeviceManager,
    #[cfg(target_arch = "x86_64")]
    pio_device_manager: PortIODeviceManager,

    // Warm-tier state — driven by pause()/resume(), read by the control socket.
    run_state: VmmRunState,
    // When the VM was last paused, so resume() can nudge the guest virtual
    // timer forward by the paused interval (freeze semantics, no clock jump).
    paused_at: Option<Instant>,
}

impl Vmm {
    /// Gets the the specified bus device.
    pub fn get_bus_device(
        &self,
        device_type: DeviceType,
        device_id: &str,
    ) -> Option<&Mutex<dyn BusDevice>> {
        self.mmio_device_manager.get_device(device_type, device_id)
    }

    /// Starts the microVM vcpus.
    pub fn start_vcpus(&mut self, mut vcpus: Vec<Vcpu>) -> Result<()> {
        let vcpu_count = vcpus.len();

        Vcpu::register_kick_signal_handler();

        self.vcpus_handles.reserve(vcpu_count);

        for mut vcpu in vcpus.drain(..) {
            vcpu.set_mmio_bus(self.mmio_device_manager.bus.clone());

            self.vcpus_handles
                .push(vcpu.start_threaded().map_err(Error::VcpuHandle)?);
        }

        // The vcpus start off in the `Paused` state, let them run. paused_ns=0
        // on the boot resume (no prior pause -> no vtimer adjustment).
        self.resume_vcpus(Duration::ZERO)?;

        Ok(())
    }

    /// Cold restore: spawn the vCPU threads in the start-paused state — each
    /// holds in its paused event loop after set_initial_state instead of
    /// cold-booting, so the orchestrator can apply the snapshot's register state
    /// (RestoreState) and then resume. Leaves the VM Paused.
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn start_vcpus_paused(&mut self, mut vcpus: Vec<Vcpu>) -> Result<()> {
        let vcpu_count = vcpus.len();
        Vcpu::register_kick_signal_handler();
        self.vcpus_handles.reserve(vcpu_count);
        for mut vcpu in vcpus.drain(..) {
            vcpu.set_mmio_bus(self.mmio_device_manager.bus.clone());
            vcpu.set_start_paused(true);
            self.vcpus_handles
                .push(vcpu.start_threaded().map_err(Error::VcpuHandle)?);
        }
        self.run_state = VmmRunState::Paused;
        self.paused_at = Some(Instant::now());
        Ok(())
    }

    /// Sends a resume command to the vcpus. `_paused_duration` is unused on
    /// Linux today (KVM guest-clock continuity on warm resume is a separate
    /// follow-up); the parameter keeps the cross-platform signature uniform.
    #[cfg(target_os = "linux")]
    pub fn resume_vcpus(&mut self, _paused_duration: Duration) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Resume)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Resumed) => (),
                _ => return Err(Error::VcpuResume),
            }
        }
        Ok(())
    }

    /// Sends a resume command to the vcpus, carrying how long they were paused
    /// so each vCPU nudges its virtual-timer offset forward (freeze semantics —
    /// the guest clock does not jump by the pause duration on resume).
    #[cfg(target_os = "macos")]
    pub fn resume_vcpus(&mut self, paused_duration: Duration) -> Result<()> {
        let paused_ns = u64::try_from(paused_duration.as_nanos()).unwrap_or(u64::MAX);
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Resume { paused_ns })
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Resumed) => (),
                _ => return Err(Error::VcpuResume),
            }
        }
        Ok(())
    }

    /// Mirror of resume_vcpus: ask each vCPU to enter Paused and wait for ack.
    /// The vCPU picks up the Pause event after `VcpuHandle::send_event` kicks it
    /// out of `hv_vcpu_run` (macOS) / its run state (Linux); see
    /// `macos/vstate.rs::handle_pending_event`.
    pub fn pause_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Pause)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Paused) => (),
                _ => return Err(Error::VcpuPause),
            }
        }
        Ok(())
    }

    pub fn run_state(&self) -> VmmRunState {
        self.run_state
    }

    /// Warm tier: freeze vCPUs without serializing state. Idempotent on Paused.
    pub fn pause(&mut self) -> Result<()> {
        match self.run_state {
            VmmRunState::Paused => Ok(()),
            VmmRunState::Running | VmmRunState::Resuming => {
                self.run_state = VmmRunState::Pausing;
                match self.pause_vcpus() {
                    Ok(()) => {
                        self.run_state = VmmRunState::Paused;
                        self.paused_at = Some(Instant::now());
                        Ok(())
                    }
                    Err(e) => {
                        // Roll the vCPUs back to Running so no Pause event is
                        // left queued (which would later freeze the guest) and
                        // a subsequent Resume isn't a no-op.
                        if self.resume_vcpus(Duration::ZERO).is_ok() {
                            self.run_state = VmmRunState::Running;
                            self.paused_at = None;
                        }
                        Err(e)
                    }
                }
            }
            VmmRunState::Pausing => Err(Error::VcpuPause),
        }
    }

    /// Warm tier: unfreeze vCPUs, nudging the guest clock forward by the paused
    /// interval. Idempotent on Running.
    pub fn resume(&mut self) -> Result<()> {
        match self.run_state {
            VmmRunState::Running => Ok(()),
            VmmRunState::Paused | VmmRunState::Pausing => {
                self.run_state = VmmRunState::Resuming;
                let paused_duration = self
                    .paused_at
                    .map(|paused_at| paused_at.elapsed())
                    .unwrap_or_default();
                match self.resume_vcpus(paused_duration) {
                    Ok(()) => {
                        self.run_state = VmmRunState::Running;
                        self.paused_at = None;
                        Ok(())
                    }
                    Err(e) => {
                        if self.pause_vcpus().is_ok() {
                            self.run_state = VmmRunState::Paused;
                            self.paused_at = Some(Instant::now());
                        }
                        Err(e)
                    }
                }
            }
            VmmRunState::Resuming => Err(Error::VcpuResume),
        }
    }

    // --- Cold tier: checkpoint / restore (macOS/HVF) ---------------------

    /// Capture every snapshot-supporting device's runtime state. Quiesce the
    /// device workers first so virtqueue indices are at a clean boundary.
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn snapshot_devices(&self) -> devices::virtio::persist::VmDevicesState {
        self.mmio_device_manager.snapshot_devices()
    }

    /// Drain + reclaim each device's worker before snapshot/restore.
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn quiesce_devices(&self) {
        self.mmio_device_manager.quiesce_devices();
    }

    /// Restart workers quiesced by [`Self::quiesce_devices`] (in-process).
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn rearm_devices(&self) {
        self.mmio_device_manager.rearm_devices();
    }

    /// Re-activate devices on a freshly-built VM from a checkpoint (cold restore).
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn restore_activate_devices(
        &self,
        state: &devices::virtio::persist::VmDevicesState,
    ) -> Result<()> {
        self.mmio_device_manager
            .restore_activate_devices(state)
            .map_err(Error::Snapshot)
    }

    /// Capture every (paused) vCPU's register state. Runs on each vCPU thread
    /// via the SaveState event (the only safe point for HVF register reads).
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn save_vcpu_states(&mut self) -> Result<Vec<vstate::VcpuState>> {
        if self.run_state != VmmRunState::Paused {
            return Err(Error::VcpuSnapshot(
                "vCPUs must be paused before capturing state".to_string(),
            ));
        }
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(vstate::VcpuEvent::SaveState)
                .map_err(Error::VcpuEvent)?;
        }
        let deadline = Instant::now() + Duration::from_secs(5);
        let mut states = Vec::with_capacity(self.vcpus_handles.len());
        for handle in self.vcpus_handles.iter() {
            states.push(Self::wait_for_saved_state(handle, deadline)?);
        }
        Ok(states)
    }

    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    fn wait_for_saved_state(handle: &VcpuHandle, deadline: Instant) -> Result<vstate::VcpuState> {
        loop {
            let remaining = deadline
                .checked_duration_since(Instant::now())
                .ok_or_else(|| Error::VcpuSnapshot("timed out capturing vCPU state".to_string()))?;
            match handle.response_receiver().recv_timeout(remaining) {
                Ok(VcpuResponse::SavedState(state)) => return Ok(*state),
                Ok(VcpuResponse::Exited(_)) => {
                    return Err(Error::VcpuSnapshot("vCPU exited during capture".to_string()))
                }
                Ok(_) => {}
                Err(_) => {
                    return Err(Error::VcpuSnapshot(
                        "channel closed while capturing vCPU state".to_string(),
                    ))
                }
            }
        }
    }

    /// Wait (until `deadline`) for a vCPU to ack the `expected` response. Matches
    /// by enum discriminant so payload-carrying responses (SavedState) compare.
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    fn wait_for_vcpu_response(
        handle: &VcpuHandle,
        expected: VcpuResponse,
        deadline: Instant,
    ) -> Result<()> {
        loop {
            let remaining = deadline
                .checked_duration_since(Instant::now())
                .ok_or(Error::VcpuPause)?;
            match handle.response_receiver().recv_timeout(remaining) {
                Ok(response)
                    if std::mem::discriminant(&response) == std::mem::discriminant(&expected) =>
                {
                    return Ok(())
                }
                Ok(VcpuResponse::Exited(_)) => return Err(Error::VcpuPause),
                Ok(_) => {}
                Err(_) => return Err(Error::VcpuPause),
            }
        }
    }

    /// Re-apply captured register state onto the (paused) restored vCPUs.
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn restore_vcpu_states(&mut self, states: Vec<vstate::VcpuState>) -> Result<()> {
        if states.len() != self.vcpus_handles.len() {
            return Err(Error::VcpuSnapshot(format!(
                "vCPU state count {} does not match vCPU count {}",
                states.len(),
                self.vcpus_handles.len()
            )));
        }
        for (handle, state) in self.vcpus_handles.iter().zip(states) {
            handle
                .send_event(vstate::VcpuEvent::RestoreState(Box::new(state)))
                .map_err(Error::VcpuEvent)?;
        }
        let deadline = Instant::now() + Duration::from_secs(5);
        for handle in self.vcpus_handles.iter() {
            Self::wait_for_vcpu_response(handle, VcpuResponse::RestoredState, deadline)
                .map_err(|_| Error::VcpuSnapshot("vCPU restore not acknowledged".to_string()))?;
        }
        Ok(())
    }

    /// Cold-to-disk checkpoint: pause, quiesce devices, capture VM/vCPU/device
    /// state, and stream guest RAM eagerly to `mem_out`. Leaves the VM paused
    /// with workers re-armed (the caller exits the process to free RAM, or
    /// resumes). Returns the checkpoint + the memory region layout.
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn checkpoint<W: std::io::Write>(
        &mut self,
        mem_out: &mut W,
    ) -> Result<(VmCheckpoint, Vec<snapshot::MemoryRegionDesc>)> {
        self.pause()?;
        self.quiesce_devices();
        let vcpu_states = self.save_vcpu_states()?;
        let vm_state = self.vm.save_state().map_err(Error::Vm)?;
        let devices = self.snapshot_devices();
        let mem_descs = snapshot::write_guest_memory(&self.guest_memory, mem_out)
            .map_err(|e| Error::Snapshot(format!("guest-memory dump: {e}")))?;
        self.rearm_devices();
        Ok((
            VmCheckpoint {
                vm_state,
                vcpu_states,
                devices,
            },
            mem_descs,
        ))
    }

    /// Cold restore (eager): load guest RAM from `mem_in` into the freshly-built
    /// guest memory (same RAM config -> same region layout as the snapshot),
    /// re-apply VM + device + vCPU state, then resume from the restored PC. The
    /// vCPUs must have been started paused ([`Self::start_vcpus_paused`]).
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub fn restore_and_resume<R: std::io::Read>(
        &mut self,
        checkpoint: VmCheckpoint,
        mem_in: &mut R,
    ) -> Result<()> {
        let descs = snapshot::region_descs(&self.guest_memory);
        snapshot::read_guest_memory_into(&self.guest_memory, &descs, mem_in)
            .map_err(|e| Error::Snapshot(format!("guest-memory load: {e}")))?;
        self.vm
            .restore_state(&checkpoint.vm_state)
            .map_err(Error::Vm)?;
        self.restore_activate_devices(&checkpoint.devices)?;
        self.restore_vcpu_states(checkpoint.vcpu_states)?;
        // Resume with paused_ns=0: the absolute CNTVOFF was already restored by
        // vcpu_restore_state, so no warm-tier delta nudge is wanted here.
        self.resume_vcpus(Duration::ZERO)?;
        self.run_state = VmmRunState::Running;
        self.paused_at = None;
        Ok(())
    }

    /// Configures the system for boot.
    pub fn configure_system(
        &self,
        vcpus: &[Vcpu],
        _intc: &IrqChip,
        initrd: &Option<InitrdConfig>,
        _smbios_oem_strings: &Option<Vec<String>>,
        _pvh: bool,
    ) -> Result<()> {
        #[cfg(target_arch = "x86_64")]
        {
            let cmdline_len = if cfg!(feature = "tee") {
                arch::x86_64::layout::CMDLINE_SEV_SIZE
            } else {
                self.kernel_cmdline.len() + 1
            };

            arch::x86_64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                vm_memory::GuestAddress(arch::x86_64::layout::CMDLINE_START),
                cmdline_len,
                initrd,
                vcpus.len() as u8,
                _pvh,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            let vcpu_mpidr = vcpus.iter().map(|cpu| cpu.get_mpidr()).collect();
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpu_mpidr,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            arch::aarch64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                _smbios_oem_strings,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "riscv64")]
        {
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpus.len() as u32,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;

            arch::riscv64::configure_system(&self.guest_memory, _smbios_oem_strings)
                .map_err(Error::ConfigureSystem)?;
        }

        Ok(())
    }

    /// Returns a reference to the inner `GuestMemoryMmap` object if present, or `None` otherwise.
    pub fn guest_memory(&self) -> &GuestMemoryMmap {
        &self.guest_memory
    }

    /// Injects CTRL+ALT+DEL keystroke combo in the i8042 device.
    #[cfg(target_arch = "x86_64")]
    pub fn send_ctrl_alt_del(&mut self) -> Result<()> {
        self.pio_device_manager
            .i8042
            .lock()
            .expect("i8042 lock was poisoned")
            .trigger_ctrl_alt_del()
            .map_err(Error::I8042Error)
    }

    /// Waits for all vCPUs to exit and terminates the Firecracker process.
    pub fn stop(&mut self, exit_code: i32) {
        info!("Vmm is stopping.");

        for observer in &self.exit_observers {
            observer
                .lock()
                .expect("Poisoned mutex for exit observer")
                .on_vmm_exit();
        }

        // Exit from Firecracker using the provided exit code. Safe because we're terminating
        // the process anyway.
        unsafe {
            libc::_exit(exit_code);
        }
    }

    /// Returns a reference to the inner KVM Vm object.
    pub fn kvm_vm(&self) -> &Vm {
        &self.vm
    }

    #[cfg(target_os = "macos")]
    pub fn add_mapping(
        &self,
        reply_sender: Sender<bool>,
        host_addr: u64,
        guest_addr: u64,
        len: u64,
    ) {
        self.vm
            .add_mapping(reply_sender, host_addr, guest_addr, len);
    }

    #[cfg(target_os = "macos")]
    pub fn remove_mapping(&self, reply_sender: Sender<bool>, guest_addr: u64, len: u64) {
        self.vm.remove_mapping(reply_sender, guest_addr, len);
    }
}

impl Subscriber for Vmm {
    /// Handle a read event (EPOLLIN).
    fn process(&mut self, event: &EpollEvent, _: &mut EventManager) {
        let source = event.fd();
        let event_set = event.event_set();

        if source == self.exit_evt.as_raw_fd() && event_set == EventSet::IN {
            let _ = self.exit_evt.read();
            // Query each vcpu for the exit_code.
            // If the exit_code can't be found on any vcpu, it means that the exit signal
            // has been issued by the i8042 controller in which case we exit with
            // FC_EXIT_CODE_OK.
            //
            // The exit code set up by the guest takes preference over the one reported
            // by either a vcpu or the i8042 controller.
            let vcpu_exit_code = self
                .vcpus_handles
                .iter()
                .find_map(|handle| match handle.response_receiver().try_recv() {
                    Ok(VcpuResponse::Exited(exit_code)) => Some(exit_code),
                    _ => None,
                })
                .unwrap_or(FC_EXIT_CODE_OK);
            let vmm_exit_code = self.exit_code.load(Ordering::SeqCst);
            let exit_code = if vmm_exit_code != i32::MAX {
                debug!("using vmm exit code: {vmm_exit_code}");
                vmm_exit_code
            } else {
                debug!("using vcpu exit code: {vcpu_exit_code}");
                vcpu_exit_code as i32
            };
            self.stop(exit_code);
        } else {
            error!("Spurious EventManager event for handler: Vmm");
        }
    }

    fn interest_list(&self) -> Vec<EpollEvent> {
        vec![EpollEvent::new(
            EventSet::IN,
            self.exit_evt.as_raw_fd() as u64,
        )]
    }
}
